---
version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: "Installing AWS-CLI"
          command: |
            sudo apt update
            sudo apt install -y awscli
      - run:
          name: "ECR Auth"
          command: aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com
      - run:
          name: building
          command: |
            docker build -t ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${REPO}:${CIRCLE_SHA1:0:10} .
            docker push ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${REPO}:${CIRCLE_SHA1:0:10}
  k8s:
    docker: 
      - image: arogudl/readytodeploy
    steps:
      - checkout
      - run:
          name: "Kubernetes"
          command: |
            ACCOUNT_ROLE=$(aws sts assume-role --role-arn ${KUBE_ROLE} --role-session-name azurdia-k8s)
            export AWS_ACCESS_KEY_ID=$(echo "${ACCOUNT_ROLE}" | jq -r '.Credentials.AccessKeyId')
            export AWS_SECRET_ACCESS_KEY=$(echo "${ACCOUNT_ROLE}" | jq -r '.Credentials.SecretAccessKey')
            export AWS_SESSION_TOKEN=$(echo "${ACCOUNT_ROLE}" | jq -r '.Credentials.SessionToken')
            aws eks update-kubeconfig --name nclouds-cluster --region ${REGION}
            helm upgrade --install azurdia-release ./azurdia-chart --namespace azurdia-ns
workflows:
  nclouds-workflow:
    jobs:
      - build
      - k8s:
          requires:
            - build
