apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "azurdia-chart.fullname" . }}
  labels:
    app: {{ template "azurdia-chart.name" . }}
  namespace: {{ .Values.app.ns.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "azurdia-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "azurdia-chart.name" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: APPLICATION
          value: {{ template "azurdia-chart.name" . }}
        ports:
        - containerPort: {{ .Values.service.port }}
        resources:
          limits:
            memory: {{ .Values.resources.limits.memory }}