apiVersion: v1
kind: Namespace
metadata:
  name: azurdia-back
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: azurdia-back
spec:
  selector:
    app: {{ template "azurdia-chart.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
