apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.app.ns.name }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.route53url }}

spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ template "azurdia-chart.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
