replicaCount: 3
image:
  repository: ncloudspublic/sample-app
  tag: latest
  pullPolicy: IfNotPresent
resources:
  limits:
    memory: 256Mi
service:
  name: azurdia-nclouds-sample-app
  port: 80
  containerPort: 3000
  type: LoadBalancer
serviceAccount:
  create: true

ingress:
  enabled: true


app:
  deployment:
    name: azurdia-deploy
  service:
    name: azurdia-svc
  ns:
    name: azurdia-ns

route53url: azurdia-project-2.training.test-something.com

hpa:
  maxReplicas: 15
  minReplicas: 3
  maxcpu: 55


autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80