apiVersion: v1
kind: Service
metadata:
  name: azurdia-nclouds-sample-app
  namespace: azurdia-namespace
spec:
  selector:
    app: nclouds
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000